export const USERID = "userId"
export const USERNAME = "username"
export const USERTOKEN = "token"
// export const myIp = "ngameagames.io";
export const myIp = "192.168.88.156";
export const serverPort = "8090";
export const createGameURL = `http://${myIp}:${serverPort}/create`;
export const loginURL = `http://${myIp}:${serverPort}/login`
export const signupURL = `http://${myIp}:${serverPort}/signup`
export const DetailsURL =  `http://${myIp}:${serverPort}/user`